### ISSUE TITLE
missing recast dependency?

### ISSUE THREAD

**Issue by junyper** [tinydoc/tinydoc-plugin-js#1]
I get the following error when I run `tinydoc run` with this plugin configured:

Error: Cannot find module 'recast'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/jstern/instructure-ui/node_modules/tinydoc-plugin-js/lib/Parser/index.js:3:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

**Comment by amireh** [comment]
uh yeah, i need to learn to use `npm prune` more often. thanks, will update soon

**Comment by amireh** [comment]
It should be good in 4.0.3, thanks for reporting.
